[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

upload_speed = 921600
monitor_speed = 115200

lib_deps = 
    knolleary/PubSubClient@^2.8
    emelianov/modbus-esp8266@^4.0.0
    bblanchon/ArduinoJson@^6.21.3

build_flags = 
    -D WIFI_SSID=\"ponchik\"
    -D WIFI_PASSWORD=\"alferovye9033298224\"
    -D MQTT_SERVER=\"192.168.1.12\"
    -D MQTT_PORT=1883
    -D DEVICE_ID=\"esp32-gateway-001\"